### ISSUE TITLE
Error on Assertions.Terminal

### ISSUE THREAD

**Issue by Travisivart** [gdt-dev/kube#4]
Getting these errors:

```
#github.com/gdt-dev/kube
../../../../go/pkg/mod/github.com/gdt-dev/kube@v1.1.2-0.20230816130031-fbe369433eba/assertions.go:456:20: ja.Terminal undefined (type "github.com/gdt-dev/gdt/types".Assertions has no field or method Terminal)
../../../../go/pkg/mod/github.com/gdt-dev/kube@v1.1.2-0.20230816130031-fbe369433eba/eval.go:120:13: a.Terminal undefined (type "github.com/gdt-dev/gdt/types".Assertions has no field or method Terminal)
FAIL    functional-gdt [build failed]
FAIL
```

I am currently using:
	github.com/gdt-dev/gdt v1.2.2-0.20230815150028-c1bed53f824d
	github.com/gdt-dev/kube v1.1.2-0.20230816130031-fbe369433eba
	
It looks like [this commit](https://github.com/gdt-dev/gdt/commit/c1bed53f824da3113b8f24bf58a4eed2bcdf8733) in the gdt package with the removal of the Terminal interface has broken the Assertions in the gdt-dev/kube pacakge:

**Comment by a-hilaly** [comment]
i think we just have to bump the `gtd-dev/gdt` version in `kube`'s module file?
/cc @jaypipes

**Comment by jaypipes** [comment]
Yeah. I just haven't gotten around to completing my PR to the kube plugin yet :)
